ci: create postflight job to control status checks

diff --git a/.github/workflows/cicd.yaml b/.github/workflows/cicd.yaml
--- a/.github/workflows/cicd.yaml
+++ b/.github/workflows/cicd.yaml
@@ -202,6 +202,24 @@ jobs:
             git push
           fi
 
+  postflight:
+    runs-on: ubuntu-latest
+    needs:
+      - build
+      - tofu
+    # Only care about this job if the trigger is a PR as it's the automerge status check
+    if: always() && github.event_name == 'pull_request'
+    steps:
+      - name: Evaluate previous job status
+        run: |
+          if [[ ${{ contains(needs.*.result, 'failure') }} == "true" ]]; then
+            echo "Failing job as some previous job has failed"
+            exit 1
+          else
+            echo "All good!"
+            exit 0
+          fi
+
   release:
     runs-on: ubuntu-latest
     needs:
